//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seed.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Seed.Localization.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, an error occurred while processing your request..
        /// </summary>
        public static string AjaxServerError {
            get {
                return ResourceManager.GetString("AjaxServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We’re sorry, but we could not find any properties for sale in {0} area. Our property listings are updated daily, so please check back soon for the latest list of {0} homes for sale. You may be interested some of our available listings in the other nearby cities..
        /// </summary>
        public static string EmptySearchResult {
            get {
                return ResourceManager.GetString("EmptySearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;T&apos; must be an enum type.
        /// </summary>
        public static string NotEnumType {
            get {
                return ResourceManager.GetString("NotEnumType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but the page you are looking for has not been found. Try cheking the URL for errors, then hit the refresh button on your browser..
        /// </summary>
        public static string ResourceNotFound {
            get {
                return ResourceManager.GetString("ResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but the page you are looking for has not been found. Try cheking the URL for errors, then hit the refresh button on your browser..
        /// </summary>
        public static string SoftResourceNotFound {
            get {
                return ResourceManager.GetString("SoftResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter valid email..
        /// </summary>
        public static string Validation_Email_Invalid {
            get {
                return ResourceManager.GetString("Validation_Email_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter your email..
        /// </summary>
        public static string Validation_Email_Required {
            get {
                return ResourceManager.GetString("Validation_Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter your full name..
        /// </summary>
        public static string Validation_Name_Required {
            get {
                return ResourceManager.GetString("Validation_Name_Required", resourceCulture);
            }
        }
    }
}
